def print_preview():
    # Prints help menu of CLI
    print("\033[1;33;40m\n",
    " PPPPPPP    OOOOOO    SSSSSSSS   TTTTTTTTTTT    IIIIIIII  TTTTTTTTTTT  !!!\n",
    " PP    PP  OOO  OOO  SSS    SSS  TTTTTTTTTTT    IIIIIIII  TTTTTTTTTTT  !!!\n",
    " PP    PP  OO    OO  SS              TTT           II         TTT      !!!\n",
    " PPPPPPP   OO    OO   SSSSSSSS       TTT           II         TTT      !!!\n",
    " PP        OO    OO          SS      TTT           II         TTT      !!!\n",
    " PP        OOO  OOO  SSS    SSS      TTT        IIIIIIII      TTT         \n",
    " PP         OOOOOO    SSSSSSSS       TTT        IIIIIIII      TTT      !!!\n",
    "\033[1;35;40m\n",
    " usage:\n", "\033[0;36;40m",
    "     post it <args>\n",
    "         Places arguments in a new post it note.\n",
    "\n",
    "     post show <delay>\n",
    "         Shows all the post it notes. Each can be displayed\n",
    "         individually with a delay if argument is given.\n",
    "\n",
    "     post clean\n",
    "         Removes all the stored notes.\n",
    "\n",
    "")
